# THIS FILE WAS AUTO GENERATED FROM THE K8S SWAGGER SPEC

require "yaml"
require "json"
require "any_hash"

module K8S::Types::Api::Core::V1::DaemonEndpoint; end

module K8S
  # Namespace holding the types for `Api::Core::V1::DaemonEndpoint`.
  #
  # NOTE: Module auto-generated by `AnyHash.define_new`.
  module Types::Api::Core::V1::DaemonEndpoint
    alias Key = String
    alias ValueType = Int32 | Nil
    # alias Value = ValueType | Array(Value) | Set(Value) | Hash(Key, Value)
    alias Instance = ::AnyHash(Key, ValueType)

    # Port number of the given endpoint.
    abstract def port : Int32
    # :ditto:
    abstract def port! : Int32
    # :ditto:
    abstract def port? : Int32?
    # :ditto:
    abstract def port=(value : Int32)
  end

  # DaemonEndpoint contains information about a single Daemon endpoint.
  @[::K8S::Properties(
    port: {key: "Port", accessor: "port", kind: "Int32", nilable: false, default: nil, read_only: false, description: "Port number of the given endpoint."},
  )]
  class Api::Core::V1::DaemonEndpoint < ::K8S::Types::Api::Core::V1::DaemonEndpoint::Instance
    include ::K8S::Types::Api::Core::V1::DaemonEndpoint
    include ::K8S::Kubernetes::Object

    # Port number of the given endpoint.
    def port : Int32
      self.["Port"].as(Int32)
    end

    # :ditto:
    def port! : Int32
      self.["Port"].as(Int32).not_nil!
    end

    # :ditto:
    def port? : Int32?
      self.["Port"]?.as(Int32?)
    end

    # :ditto:
    def port=(value : Int32)
      self.["Port"] = value
    end

    macro finished
      ::K8S::Kubernetes::Resource.define_serialize_methods([
        { key: "Port", accessor: "port", nilable: false, read_only: false, default: nil, kind: Int32 },
      ])
end
  end
end
