# THIS FILE WAS AUTO GENERATED FROM THE K8S SWAGGER SPEC

require "yaml"
require "json"
require "any_hash"

module K8S::Types::Api::Core::V1::HTTPHeader; end

module K8S
  # Namespace holding the types for `Api::Core::V1::HTTPHeader`.
  #
  # NOTE: Module auto-generated by `AnyHash.define_new`.
  module Types::Api::Core::V1::HTTPHeader
    alias Key = String
    alias ValueType = String | Nil
    # alias Value = ValueType | Array(Value) | Set(Value) | Hash(Key, Value)
    alias Instance = ::AnyHash(Key, ValueType)

    # The header field name
    abstract def name : String
    # :ditto:
    abstract def name! : String
    # :ditto:
    abstract def name? : String?
    # :ditto:
    abstract def name=(value : String)
    # The header field value
    abstract def value : String
    # :ditto:
    abstract def value! : String
    # :ditto:
    abstract def value? : String?
    # :ditto:
    abstract def value=(value : String)
  end

  # HTTPHeader describes a custom header to be used in HTTP probes
  @[::K8S::Properties(
    name: {key: "name", accessor: "name", kind: "String", nilable: false, default: nil, read_only: false, description: "The header field name"},
    value: {key: "value", accessor: "value", kind: "String", nilable: false, default: nil, read_only: false, description: "The header field value"},
  )]
  class Api::Core::V1::HTTPHeader < ::K8S::Types::Api::Core::V1::HTTPHeader::Instance
    include ::K8S::Types::Api::Core::V1::HTTPHeader
    include ::K8S::Kubernetes::Object

    # The header field name
    def name : String
      self.["name"].as(String)
    end

    # :ditto:
    def name! : String
      self.["name"].as(String).not_nil!
    end

    # :ditto:
    def name? : String?
      self.["name"]?.as(String?)
    end

    # :ditto:
    def name=(value : String)
      self.["name"] = value
    end

    # The header field value
    def value : String
      self.["value"].as(String)
    end

    # :ditto:
    def value! : String
      self.["value"].as(String).not_nil!
    end

    # :ditto:
    def value? : String?
      self.["value"]?.as(String?)
    end

    # :ditto:
    def value=(value : String)
      self.["value"] = value
    end

    macro finished
      ::K8S::Kubernetes::Resource.define_serialize_methods([
        { key: "name", accessor: "name", nilable: false, read_only: false, default: nil, kind: String },
        { key: "value", accessor: "value", nilable: false, read_only: false, default: nil, kind: String },
      ])
end
  end
end
