# THIS FILE WAS AUTO GENERATED FROM THE K8S SWAGGER SPEC

require "yaml"
require "json"
require "any_hash"

module K8S::Types::Api::Apps::V1beta1::ScaleSpec; end

module K8S
  # Namespace holding the types for `Api::Apps::V1beta1::ScaleSpec`.
  #
  # NOTE: Module auto-generated by `AnyHash.define_new`.
  module Types::Api::Apps::V1beta1::ScaleSpec
    alias Key = String
    alias ValueType = Int32 | Nil
    # alias Value = ValueType | Array(Value) | Set(Value) | Hash(Key, Value)
    alias Instance = ::AnyHash(Key, ValueType)

    # desired number of instances for the scaled object.
    abstract def replicas : Int32?
    # :ditto:
    abstract def replicas! : Int32
    # :ditto:
    abstract def replicas? : Int32?
    # :ditto:
    abstract def replicas=(value : Int32?)
  end

  # ScaleSpec describes the attributes of a scale subresource
  @[::K8S::Properties(
    replicas: {key: "replicas", accessor: "replicas", kind: "Int32", nilable: true, default: nil, read_only: false, description: "desired number of instances for the scaled object."},
  )]
  class Api::Apps::V1beta1::ScaleSpec < ::K8S::Types::Api::Apps::V1beta1::ScaleSpec::Instance
    include ::K8S::Types::Api::Apps::V1beta1::ScaleSpec
    include ::K8S::Kubernetes::Object

    # desired number of instances for the scaled object.
    def replicas : Int32?
      self.["replicas"].as(Int32?)
    end

    # :ditto:
    def replicas! : Int32
      self.["replicas"].as(Int32?).not_nil!
    end

    # :ditto:
    def replicas? : Int32?
      self.["replicas"]?.as(Int32?)
    end

    # :ditto:
    def replicas=(value : Int32?)
      self.["replicas"] = value
    end

    macro finished
      ::K8S::Kubernetes::Resource.define_serialize_methods([
        { key: "replicas", accessor: "replicas", nilable: true, read_only: false, default: nil, kind: Int32 },
      ])
end
  end
end
