# THIS FILE WAS AUTO GENERATED FROM THE K8S SWAGGER SPEC

require "yaml"
require "json"
require "any_hash"

module K8S::Types::Api::Extensions::V1beta1::NetworkPolicyPeer; end

require "./ip_block"
require "../../../apimachinery/apis/meta/v1/label_selector"

module K8S
  # Namespace holding the types for `Api::Extensions::V1beta1::NetworkPolicyPeer`.
  #
  # NOTE: Module auto-generated by `AnyHash.define_new`.
  module Types::Api::Extensions::V1beta1::NetworkPolicyPeer
    alias Key = String
    alias ValueType = ::K8S::Api::Extensions::V1beta1::IPBlock | ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector | Nil
    # alias Value = ValueType | Array(Value) | Set(Value) | Hash(Key, Value)
    alias Instance = ::AnyHash(Key, ValueType)

    # IPBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be.
    abstract def ip_block : ::K8S::Api::Extensions::V1beta1::IPBlock?
    # :ditto:
    abstract def ip_block! : ::K8S::Api::Extensions::V1beta1::IPBlock
    # :ditto:
    abstract def ip_block? : ::K8S::Api::Extensions::V1beta1::IPBlock?
    # :ditto:
    abstract def ip_block=(value : ::K8S::Api::Extensions::V1beta1::IPBlock?)
    # Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.
    #
    # If PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.
    abstract def namespace_selector : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
    # :ditto:
    abstract def namespace_selector! : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector
    # :ditto:
    abstract def namespace_selector? : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
    # :ditto:
    abstract def namespace_selector=(value : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
    # This is a label selector which selects Pods. This field follows standard label selector semantics; if present but empty, it selects all pods.
    #
    # If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the Pods matching PodSelector in the policy's own Namespace.
    abstract def pod_selector : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
    # :ditto:
    abstract def pod_selector! : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector
    # :ditto:
    abstract def pod_selector? : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
    # :ditto:
    abstract def pod_selector=(value : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
  end

  # DEPRECATED 1.9 - This group version of NetworkPolicyPeer is deprecated by [networking/v1/NetworkPolicyPeer.](networking/v1/NetworkPolicyPeer.)
  @[::K8S::Properties(
    ip_block: {key: "ipBlock", accessor: "ip_block", kind: "::K8S::Api::Extensions::V1beta1::IPBlock", nilable: true, default: nil, read_only: false, description: "IPBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be."},
    namespace_selector: {key: "namespaceSelector", accessor: "namespace_selector", kind: "::K8S::Apimachinery::Apis::Meta::V1::LabelSelector", nilable: true, default: nil, read_only: false, description: "Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.\n\nIf PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector."},
    pod_selector: {key: "podSelector", accessor: "pod_selector", kind: "::K8S::Apimachinery::Apis::Meta::V1::LabelSelector", nilable: true, default: nil, read_only: false, description: "This is a label selector which selects Pods. This field follows standard label selector semantics; if present but empty, it selects all pods.\n\nIf NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the Pods matching PodSelector in the policy's own Namespace."},
  )]
  class Api::Extensions::V1beta1::NetworkPolicyPeer < ::K8S::Types::Api::Extensions::V1beta1::NetworkPolicyPeer::Instance
    include ::K8S::Types::Api::Extensions::V1beta1::NetworkPolicyPeer
    include ::K8S::Kubernetes::Object

    # IPBlock defines policy on a particular IPBlock. If this field is set then neither of the other fields can be.
    def ip_block : ::K8S::Api::Extensions::V1beta1::IPBlock?
      self.["ipBlock"].as(::K8S::Api::Extensions::V1beta1::IPBlock?)
    end

    # :ditto:
    def ip_block! : ::K8S::Api::Extensions::V1beta1::IPBlock
      self.["ipBlock"].as(::K8S::Api::Extensions::V1beta1::IPBlock?).not_nil!
    end

    # :ditto:
    def ip_block? : ::K8S::Api::Extensions::V1beta1::IPBlock?
      self.["ipBlock"]?.as(::K8S::Api::Extensions::V1beta1::IPBlock?)
    end

    # :ditto:
    def ip_block=(value : ::K8S::Api::Extensions::V1beta1::IPBlock?)
      self.["ipBlock"] = value
    end

    # Selects Namespaces using cluster-scoped labels. This field follows standard label selector semantics; if present but empty, it selects all namespaces.
    #
    # If PodSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected by NamespaceSelector.
    def namespace_selector : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
      self.["namespaceSelector"].as(::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
    end

    # :ditto:
    def namespace_selector! : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector
      self.["namespaceSelector"].as(::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?).not_nil!
    end

    # :ditto:
    def namespace_selector? : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
      self.["namespaceSelector"]?.as(::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
    end

    # :ditto:
    def namespace_selector=(value : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
      self.["namespaceSelector"] = value
    end

    # This is a label selector which selects Pods. This field follows standard label selector semantics; if present but empty, it selects all pods.
    #
    # If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole selects the Pods matching PodSelector in the Namespaces selected by NamespaceSelector. Otherwise it selects the Pods matching PodSelector in the policy's own Namespace.
    def pod_selector : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
      self.["podSelector"].as(::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
    end

    # :ditto:
    def pod_selector! : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector
      self.["podSelector"].as(::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?).not_nil!
    end

    # :ditto:
    def pod_selector? : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?
      self.["podSelector"]?.as(::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
    end

    # :ditto:
    def pod_selector=(value : ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector?)
      self.["podSelector"] = value
    end

    macro finished
      ::K8S::Kubernetes::Resource.define_serialize_methods([
        { key: "ipBlock", accessor: "ip_block", nilable: true, read_only: false, default: nil, kind: ::K8S::Api::Extensions::V1beta1::IPBlock },
        { key: "namespaceSelector", accessor: "namespace_selector", nilable: true, read_only: false, default: nil, kind: ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector },
        { key: "podSelector", accessor: "pod_selector", nilable: true, read_only: false, default: nil, kind: ::K8S::Apimachinery::Apis::Meta::V1::LabelSelector },
      ])
end
  end
end
