# THIS FILE WAS AUTO GENERATED FROM THE K8S SWAGGER SPEC

require "yaml"
require "json"
require "any_hash"

module K8S::Types::Api::Autoscaling::V2beta2::MetricValueStatus; end

module K8S
  # Namespace holding the types for `Api::Autoscaling::V2beta2::MetricValueStatus`.
  #
  # NOTE: Module auto-generated by `AnyHash.define_new`.
  module Types::Api::Autoscaling::V2beta2::MetricValueStatus
    alias Key = String
    alias ValueType = Int32 | ::Int32 | ::String | Nil
    # alias Value = ValueType | Array(Value) | Set(Value) | Hash(Key, Value)
    alias Instance = ::AnyHash(Key, ValueType)

    # currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
    abstract def average_utilization : Int32?
    # :ditto:
    abstract def average_utilization! : Int32
    # :ditto:
    abstract def average_utilization? : Int32?
    # :ditto:
    abstract def average_utilization=(value : Int32?)
    # averageValue is the current value of the average of the metric across all relevant pods (as a quantity)
    abstract def average_value : ::Int32 | ::String?
    # :ditto:
    abstract def average_value! : ::Int32 | ::String
    # :ditto:
    abstract def average_value? : ::Int32 | ::String?
    # :ditto:
    abstract def average_value=(value : ::Int32 | ::String?)
    # value is the current value of the metric (as a quantity).
    abstract def value : ::Int32 | ::String?
    # :ditto:
    abstract def value! : ::Int32 | ::String
    # :ditto:
    abstract def value? : ::Int32 | ::String?
    # :ditto:
    abstract def value=(value : ::Int32 | ::String?)
  end

  # MetricValueStatus holds the current value for a metric
  @[::K8S::Properties(
    average_utilization: {key: "averageUtilization", accessor: "average_utilization", kind: "Int32", nilable: true, default: nil, read_only: false, description: "currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods."},
    average_value: {key: "averageValue", accessor: "average_value", kind: "::Int32 | ::String", nilable: true, default: nil, read_only: false, description: "averageValue is the current value of the average of the metric across all relevant pods (as a quantity)"},
    value: {key: "value", accessor: "value", kind: "::Int32 | ::String", nilable: true, default: nil, read_only: false, description: "value is the current value of the metric (as a quantity)."},
  )]
  class Api::Autoscaling::V2beta2::MetricValueStatus < ::K8S::Types::Api::Autoscaling::V2beta2::MetricValueStatus::Instance
    include ::K8S::Types::Api::Autoscaling::V2beta2::MetricValueStatus
    include ::K8S::Kubernetes::Object

    # currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.
    def average_utilization : Int32?
      self.["averageUtilization"].as(Int32?)
    end

    # :ditto:
    def average_utilization! : Int32
      self.["averageUtilization"].as(Int32?).not_nil!
    end

    # :ditto:
    def average_utilization? : Int32?
      self.["averageUtilization"]?.as(Int32?)
    end

    # :ditto:
    def average_utilization=(value : Int32?)
      self.["averageUtilization"] = value
    end

    # averageValue is the current value of the average of the metric across all relevant pods (as a quantity)
    def average_value : ::Int32 | ::String?
      self.["averageValue"].as(::Int32 | ::String?)
    end

    # :ditto:
    def average_value! : ::Int32 | ::String
      self.["averageValue"].as(::Int32 | ::String?).not_nil!
    end

    # :ditto:
    def average_value? : ::Int32 | ::String?
      self.["averageValue"]?.as(::Int32 | ::String?)
    end

    # :ditto:
    def average_value=(value : ::Int32 | ::String?)
      self.["averageValue"] = value
    end

    # value is the current value of the metric (as a quantity).
    def value : ::Int32 | ::String?
      self.["value"].as(::Int32 | ::String?)
    end

    # :ditto:
    def value! : ::Int32 | ::String
      self.["value"].as(::Int32 | ::String?).not_nil!
    end

    # :ditto:
    def value? : ::Int32 | ::String?
      self.["value"]?.as(::Int32 | ::String?)
    end

    # :ditto:
    def value=(value : ::Int32 | ::String?)
      self.["value"] = value
    end

    macro finished
      ::K8S::Kubernetes::Resource.define_serialize_methods([
        { key: "averageUtilization", accessor: "average_utilization", nilable: true, read_only: false, default: nil, kind: Int32 },
        { key: "averageValue", accessor: "average_value", nilable: true, read_only: false, default: nil, kind: ::Union(::Int32 | ::String) },
        { key: "value", accessor: "value", nilable: true, read_only: false, default: nil, kind: ::Union(::Int32 | ::String) },
      ])
end
  end
end
