# THIS FILE WAS AUTO GENERATED FROM THE K8S SWAGGER SPEC

require "yaml"
require "json"
require "any_hash"

module K8S::Types::Api::Autoscaling::V2beta2::ObjectMetricStatus; end

require "./metric_value_status"
require "./cross_version_object_reference"
require "./metric_identifier"

module K8S
  # Namespace holding the types for `Api::Autoscaling::V2beta2::ObjectMetricStatus`.
  #
  # NOTE: Module auto-generated by `AnyHash.define_new`.
  module Types::Api::Autoscaling::V2beta2::ObjectMetricStatus
    alias Key = String
    alias ValueType = ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus | ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference | ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier | Nil
    # alias Value = ValueType | Array(Value) | Set(Value) | Hash(Key, Value)
    alias Instance = ::AnyHash(Key, ValueType)

    # current contains the current value for the given metric
    abstract def current : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus
    # :ditto:
    abstract def current! : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus
    # :ditto:
    abstract def current? : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus?
    # :ditto:
    abstract def current=(value : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus)
    #
    abstract def described_object : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference
    # :ditto:
    abstract def described_object! : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference
    # :ditto:
    abstract def described_object? : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference?
    # :ditto:
    abstract def described_object=(value : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference)
    # metric identifies the target metric by name and selector
    abstract def metric : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier
    # :ditto:
    abstract def metric! : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier
    # :ditto:
    abstract def metric? : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier?
    # :ditto:
    abstract def metric=(value : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier)
  end

  # ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
  @[::K8S::Properties(
    current: {key: "current", accessor: "current", kind: "::K8S::Api::Autoscaling::V2beta2::MetricValueStatus", nilable: false, default: nil, read_only: false, description: "current contains the current value for the given metric"},
    described_object: {key: "describedObject", accessor: "described_object", kind: "::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference", nilable: false, default: nil, read_only: false, description: nil},
    metric: {key: "metric", accessor: "metric", kind: "::K8S::Api::Autoscaling::V2beta2::MetricIdentifier", nilable: false, default: nil, read_only: false, description: "metric identifies the target metric by name and selector"},
  )]
  class Api::Autoscaling::V2beta2::ObjectMetricStatus < ::K8S::Types::Api::Autoscaling::V2beta2::ObjectMetricStatus::Instance
    include ::K8S::Types::Api::Autoscaling::V2beta2::ObjectMetricStatus
    include ::K8S::Kubernetes::Object

    # current contains the current value for the given metric
    def current : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus
      self.["current"].as(::K8S::Api::Autoscaling::V2beta2::MetricValueStatus)
    end

    # :ditto:
    def current! : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus
      self.["current"].as(::K8S::Api::Autoscaling::V2beta2::MetricValueStatus).not_nil!
    end

    # :ditto:
    def current? : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus?
      self.["current"]?.as(::K8S::Api::Autoscaling::V2beta2::MetricValueStatus?)
    end

    # :ditto:
    def current=(value : ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus)
      self.["current"] = value
    end

    #
    def described_object : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference
      self.["describedObject"].as(::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference)
    end

    # :ditto:
    def described_object! : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference
      self.["describedObject"].as(::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference).not_nil!
    end

    # :ditto:
    def described_object? : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference?
      self.["describedObject"]?.as(::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference?)
    end

    # :ditto:
    def described_object=(value : ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference)
      self.["describedObject"] = value
    end

    # metric identifies the target metric by name and selector
    def metric : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier
      self.["metric"].as(::K8S::Api::Autoscaling::V2beta2::MetricIdentifier)
    end

    # :ditto:
    def metric! : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier
      self.["metric"].as(::K8S::Api::Autoscaling::V2beta2::MetricIdentifier).not_nil!
    end

    # :ditto:
    def metric? : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier?
      self.["metric"]?.as(::K8S::Api::Autoscaling::V2beta2::MetricIdentifier?)
    end

    # :ditto:
    def metric=(value : ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier)
      self.["metric"] = value
    end

    macro finished
      ::K8S::Kubernetes::Resource.define_serialize_methods([
        { key: "current", accessor: "current", nilable: false, read_only: false, default: nil, kind: ::K8S::Api::Autoscaling::V2beta2::MetricValueStatus },
        { key: "describedObject", accessor: "described_object", nilable: false, read_only: false, default: nil, kind: ::K8S::Api::Autoscaling::V2beta2::CrossVersionObjectReference },
        { key: "metric", accessor: "metric", nilable: false, read_only: false, default: nil, kind: ::K8S::Api::Autoscaling::V2beta2::MetricIdentifier },
      ])
end
  end
end
