# This CI job installs Crystal and shard dependencies, then executes `crystal spec` to run the test suite
# More configuration options are available at https://crystal-lang.github.io/install-crystal/configurator.html

on:
  release:
    types:
      - published
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install shards
        run: shards update --ignore-crystal-version
      - name: Build docs
        run: crystal ./bin/gen_docs.cr
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
